/* Generated By:JavaCC: Do not edit this line. S5jConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S5jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int EXTERN = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int READINT = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int PRINTLN = 17;
  /** RegularExpression Id. */
  int UNSIGNED = 18;
  /** RegularExpression Id. */
  int ID = 19;
  /** RegularExpression Id. */
  int ASSIGN = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int LEFTPAREN = 22;
  /** RegularExpression Id. */
  int RIGHTPAREN = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int TIMES = 26;
  /** RegularExpression Id. */
  int FORWARDSLASH = 27;
  /** RegularExpression Id. */
  int LEFTBRACE = 28;
  /** RegularExpression Id. */
  int RIGHTBRACE = 29;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int ERROR = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"\\\"\"",
    "\",\"",
    "\"void\"",
    "\"extern\"",
    "\"int\"",
    "\"do\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"readint\"",
    "\"print\"",
    "\"println\"",
    "<UNSIGNED>",
    "<ID>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "<token of kind 32>",
    "\"\\\\\\r\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "<token of kind 36>",
    "\"\\\"\"",
    "<ERROR>",
  };

}
