/* Generated By:JavaCC: Do not edit this line. S3jConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S3jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int READINT = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int PRINTLN = 8;
  /** RegularExpression Id. */
  int UNSIGNED = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int LEFTPAREN = 14;
  /** RegularExpression Id. */
  int RIGHTPAREN = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int TIMES = 18;
  /** RegularExpression Id. */
  int FORWARDSLASH = 19;
  /** RegularExpression Id. */
  int LEFTBRACE = 20;
  /** RegularExpression Id. */
  int RIGHTBRACE = 21;
  /** RegularExpression Id. */
  int ERROR = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"readint\"",
    "\"print\"",
    "\"println\"",
    "<UNSIGNED>",
    "<ID>",
    "<STRING>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "<ERROR>",
  };

}
