/* Generated By:JavaCC: Do not edit this line. S4jConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S4jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int READINT = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int PRINTLN = 13;
  /** RegularExpression Id. */
  int UNSIGNED = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int LEFTPAREN = 18;
  /** RegularExpression Id. */
  int RIGHTPAREN = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int TIMES = 22;
  /** RegularExpression Id. */
  int FORWARDSLASH = 23;
  /** RegularExpression Id. */
  int LEFTBRACE = 24;
  /** RegularExpression Id. */
  int RIGHTBRACE = 25;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int ERROR = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"\\\"\"",
    "\"do\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"readint\"",
    "\"print\"",
    "\"println\"",
    "<UNSIGNED>",
    "<ID>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "<token of kind 28>",
    "\"\\\\\\r\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "<token of kind 32>",
    "\"\\\"\"",
    "<ERROR>",
  };

}
